apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - name: redis-port
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:alpine
          volumeMounts:
            - name: redis-data
              mountPath: /data
          # AOF activated, RDB activated, every 15 min if at least 1 key changed,
          # every 5 min if at least 10 keys changed, every 1 min if at least 10000 keys changed
          command: ["redis-server", "--appendonly", "yes", "--save", "900", "1", "--save", "300", "10", "--save", "60", "10000"]
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            exec:
              command:
                - redis-cli
                - ping
            failureThreshold: 10
            periodSeconds: 1

      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc

