apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: ticketing
build:
  local:
    push: false
  artifacts:
  - image: jym272/ticketing-tickets-api
    context: tickets-api
    docker:
      dockerfile: dev.Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: /app
  - image: jym272/ticketing-auth-api
    context: auth-api
    docker:
      dockerfile: dev.Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: /app
  - image: jym272/ticketing-frontend
    context: client
    docker:
      dockerfile: dev.Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: /app
        - src: 'src/**/*.tsx'
          dest: /app
  - image: jym272/ticketing-orders-api
    context: orders-api
    docker:
      dockerfile: dev.Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: /app
manifests:
  kustomize:
    paths:
    - k8s/base
profiles:
- name: local
  manifests:
    kustomize:
      paths:
      - k8s/overlay/local
