apiVersion: v1
kind: PersistentVolume
metadata:
  name: jetstream-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    server: 192.168.122.1
    path: /data/jetstream
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jetstream-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
