apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jetstream-sc
provisioner: kubernetes.io/no-provisioner
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jetstream-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: jetstream-sc
  nfs:
    server: 192.168.122.1
    path: /data/jetstream
