apiVersion: v1
kind: Service
metadata:
  name: adminer
spec:
  selector:
    app: adminer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  labels:
    env: dev
  annotations:
    datree.skip/CONTAINERS_MISSING_READINESSPROBE_KEY: irrelevant for this deployment.
    datree.skip/CONTAINERS_MISSING_LIVENESSPROBE_KEY: irrelevant for this deployment.
    datree.skip/CONTAINERS_INCORRECT_RUNASNONROOT_VALUE: adminer is not used in production.
    datree.skip/CONTAINERS_INCORRECT_READONLYROOTFILESYSTEM_VALUE: adminer is not used in production.
spec:
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer:4
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              drop: [ "NET_RAW" ]
            allowPrivilegeEscalation: false
          env:
            - name: ADMINER_DESIGN
              value: dracula
          resources:
            limits:
              memory: 128Mi
              cpu: 20m
            requests:
              memory: 64Mi
              cpu: 10m