apiVersion: v1
kind: Service
metadata:
  name: db-orders-svc
spec:
  clusterIP: None
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
    protocol: TCP 
  selector:
    db: orders

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: db-orders
#spec:
#  clusterIP: None
#  selector:
#    db: orders
#  ports:
#    - protocol: TCP
#      port: 5432
#      name: postgres
#---