resources:
  - ../../base/
  - ../../base/hpa
  - ../../base/postgres-db
  - ../../base/postgres-db-ha/
  - sealedSecrets
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- patch: |-
    - op: add
      path: /spec/volumeClaimTemplates/0/spec/storageClassName
      value: do-block-storage
  target:
    name: db-auth
    kind: StatefulSet
- patch: |-
    - op: add
      path: /spec/volumeClaimTemplates/0/spec/storageClassName
      value: do-block-storage
  target:
    name: postgres-sts-orders
    kind: StatefulSet
- patch: |-
    - op: add
      path: /spec/volumeClaimTemplates/0/spec/storageClassName
      value: do-block-storage
  target:
    name: db-payments
    kind: StatefulSet
- patch: |-
    - op: add
      path: /spec/volumeClaimTemplates/0/spec/storageClassName
      value: do-block-storage
  target:
    name: postgres-sts-tickets
    kind: StatefulSet
- patch: |-
    - op: add
      path: /spec/volumeClaimTemplates/0/spec/storageClassName
      value: do-block-storage
  target:
    name: redis
    kind: StatefulSet
- patch: |-
    - op: add
      path: /spec/volumeClaimTemplates/0/spec/storageClassName
      value: do-block-storage
  target:
    name: nats
    kind: StatefulSet
# set INGRESS_NS and INGRESS_SVC env vars for frontend
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: default
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: nginx-ingress-ingress-nginx-controller
  target:
    kind: Deployment
    name: frontend
# set stage in env label for Deployment
- patch: |-
    - op: replace
      path: /metadata/labels/env
      value: stage
  target:
    kind: Deployment
    name: expiration-api
- patch: |-
    - op: replace
      path: /metadata/labels/env
      value: stage
  target:
    kind: Deployment
    name: auth-api
- patch: |-
    - op: replace
      path: /metadata/labels/env
      value: stage
  target:
    kind: Deployment
    name: orders-api
- patch: |-
    - op: replace
      path: /metadata/labels/env
      value: stage
  target:
    kind: Deployment
    name: tickets-api
- patch: |-
    - op: replace
      path: /metadata/labels/env
      value: stage
  target:
    kind: Deployment
    name: payments-api
- patch: |-
    - op: replace
      path: /metadata/labels/env
      value: stage
  target:
    kind: Deployment
    name: frontend
