resources:
- ../../base/
- ingress.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
# init container lookup for postgres server host
- path: patches/apis-init-container-cmd.yaml
  target:
    kind: Deployment
    name: auth-api
- path: patches/apis-init-container-cmd.yaml
  target:
      kind: Deployment
      name: orders-api
- path: patches/apis-init-container-cmd.yaml
  target:
    kind: Deployment
    name: payments-api
- path: patches/apis-init-container-cmd.yaml
  target:
    kind: Deployment
    name: tickets-api
# take out the volumeMounts and volumes from redis and nats
- patch: |-
    - op: remove
      path: /spec/template/spec/containers/0/volumeMounts
    - op: remove
      path: /spec/template/spec/volumes
  target:
    name: redis-deployment
    kind: Deployment
- patch: |-
    - op: remove
      path: /spec/template/spec/containers/0/volumeMounts
    - op: remove
      path: /spec/template/spec/volumes
  target:
    kind: Deployment
    name: nats
# set INGRESS_NS and INGRESS_SVC env vars for frontend
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: default
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: nginx-ingress-ingress-nginx-controller
  target:
    kind: Deployment
    name: frontend

secretGenerator:
  - name: postgres-secret
    envs:
      - .postgres.secret
configMapGenerator:
  - name: postgres-host
    envs:
      - .postgres_host.env