apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-postgres
          imagePullPolicy: IfNotPresent
          image: busybox:1.36.0
          command:
            [
              "sh",
              "-c",
              "until nc -vz ls-0b45e622b2611858ef29275da010f4ca056feac5.ccbqxi7wrom4.us-east-2.rds.amazonaws.com 5432; do echo waiting for db payments; sleep 2; done",
            ]
      containers:
        - name: auth-api
          env:
            - name: POSTGRES_PASSWORD
              value: "U+^Si8mD[m+spAC}zPq!RO{ZGuD8mJ4Y"
            - name: POSTGRES_HOST
              value: ls-0b45e622b2611858ef29275da010f4ca056feac5.ccbqxi7wrom4.us-east-2.rds.amazonaws.com
  selector:
    matchLabels:
      api: auth
