resources:
  - ../../base/
  - ../../base/adminer
  - ../../base/ingress
  - ../../base/postgres-db/
  - ../../base/storage
  - postgres-secret.yaml
#secretGenerator:
#  - name: postgres-secret
#    envs:
#      - .postgres.secret