resources:
  - ../../base/
  - ../../base/adminer
  - ../../base/ingress
  - ../../base/postgres-db/
  - ../../base/postgres-db-ha/
  - ../../base/hpa
  - sealedSecrets
patches:
  # ---------------- Patch PV volumes from hostPath to NFS --------------
  # nats
  - patch: |-
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: jetstream-sc
    target:
      name: nats
      kind: StatefulSet
  # redis
  - patch: |-
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: redis-sc
    target:
      name: redis
      kind: StatefulSet
  # postgres-auth
  - patch: |-
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: postgres-auth-sc
    target:
      name: db-auth
      kind: StatefulSet
  # postgres-ha-orders
  - patch: |-
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: postgres-orders-sc
    target:
      name: postgres-sts-orders
      kind: StatefulSet
  # postgres-payments
  - patch: |-
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value:  postgres-payments-sc
    target:
      name: db-payments
      kind: StatefulSet
  # postgres-tickets
  - patch: |-
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: postgres-tickets-sc
    target:
      name: postgres-sts-tickets
      kind: StatefulSet
  # ----------------------------- Patch node name ----------------------------------
  # grouping StatefulSet to nodes:
  # multinodes-m02 -> nats, redis
  # multinodes-m03 -> auth, payments
  # multinodes-m03 -> tickets, orders
#  - patch: |-
#      - op: add
#        path: /spec/template/spec/nodeName
#        value: multinodes-m02
#    target:
#      name: redis
#      kind: StatefulSet
#  - patch: |-
#      - op: add
#        path: /spec/template/spec/nodeName
#        value: multinodes-m02
#    target:
#      name: nats
#      kind: StatefulSet
#  - patch: |-
#      - op: add
#        path: /spec/template/spec/nodeName
#        value: multinodes-m03
#    target:
#      name: db-auth
#      kind: StatefulSet
#  - patch: |-
#      - op: add
#        path: /spec/template/spec/nodeName
#        value: multinodes-m03
#    target:
#      name: db-payments
#      kind: StatefulSet
#  - patch: |-
#      - op: add
#        path: /spec/template/spec/nodeName
#        value: multinodes-m04
#    target:
#      name: postgres-sts-orders
#      kind: StatefulSet
#  - patch: |-
#      - op: add
#        path: /spec/template/spec/nodeName
#        value: multinodes-m04
#    target:
#      name: postgres-sts-tickets
#      kind: StatefulSet
