apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBqujiNANyrujtlyldPOH/aDSgbgD4+3zsMvPPHVRwuC2JpbcxJ0/cFBGqHnw3CbPqq3lkrL/coos8sTGe4kmC1w6is7ZgRX2dMd1mqhXdVx2pJ6pMNsrZ1uj0Ai9HfOjulNjOFBP7Z90Wp1VzxaifLIJQ5m/5ymL4um2TK8nudUGX3aBmQxVxpOQw8Ovl4tQhxVEPBzqzlzRWjut/38rJW9TAUOjUtqxiVQxcz9VCMlLTFCKs4KX3CwmWFKPRkhCnRRii2HU156+0ABxPYxyZXhzAMqN+9ghKUUSnfEeON9sUQN6pSk1G1TkdJly9rrDR9VjtqOMWtPR53D8sVn5jcSIfHTAGpEtvBI27fVdBrNKRmVEuP7SZTfeg90mrhF9+LAOUN64Oz/9nVA60GM/MUw66s9kw5Atvd6Vt9eIvyHeCNGs9xMq4GbxsLLiBtcJPj29wsBh2dx4yPCCwBdBzRy8IpUt5Kwi495GeVmKCS/b/KOGhXUPLIpo9QwT1hKTCQpHxXl6U+5Jdh2KSsKiSLaOsEHcwFgtxkoTnOaFhXn7sYx1/avwo60uKi1NwSvbGmZ1BOokckf8IDCdF0GdHKcTfLUqUDl/QUq7F94GSeYcfVWtfbaKXh5L4PrJq+6iOQm4uMH3Slwu7nSZJKQskMJ7grGgQQfIm2Qfj8k0XiDLWYVGEU5v2Ug1XCvX5NgdrlNsVbUoc=
    POSTGRES_USER: AgA1zZuSq0KwRSU/k53Vt3+74y4rsdjO9t2fEqN2ClrLHwyv1fVwHre8ToP01jEP1NGJ0cVM8ozvusVK7qoCOoZOHNaA7QTUsKT+oKufJlOxLdjPHMhXWstcOQDQIvXRSUQkCGAU3EeDaDz4VbjATZ9DmMLxzNVfI1guhia1EPk4jrehy5iJX3xb4FCs7ofdN7jLNk2QjLcBvN+iHTDxoI5ni2SMiyi6cLwgPFa5r94WfwSmD6pbjpHUHUXRHE6hJ56w3c5Wegs2QVouztXV70hE+j872ENcdTttkgxcSrkVfiNIvGex/ScVIDhQIP/uCH83ewyC8naTQO2qs+FinvT1i/nUSWs6Z4GuDJgZRl+330ywog0kVvwOOOvo9/yKsSSiBXSZ9h/DVeycbkVHAnhy/3dmQWSnA73gPmQPIWzmaW4sOB6+h+kMQkkUUgYC9+lELQ2CjNrAbIgOjZef0riNxt9vn/zieuKKTUZdGrHY1oJBIMwf1Skhk55cAbsVRLsEsuqdpAoGN01+yFNHEXrrJpILVaLktv2gyOdh4ENGCswqAGS8Bto777tceu2yzmeIjViFluu2RZIIDUqdfbnkt/o20EldHmlIq7/wT5b3tK6j10s2jGLxCXOvvKiCC3kSzoM4kDD66PcIqGkgQzFOjUvtAVUyXDDnpXrekXXsgRMoJjyArI/Us19/VJxqtOrXRaI2gQ==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: default

