apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCBjz79sU3OxsEIrPtiGPhnDbK9S9tVsEBzG6POn+qcV2bst1dGW6DEdQmXlLFhhDPYAQFpJWdL70/TzQtq50JQB9TLx+i5cNNWH4jv4kNlsxJFNqYejAFkGcBbeHM33l3/GmKmUUt0Sih7K60wr/ntEjFfIMB1CoOi2W1rb0ZzUT328qJZRJAG+2ZKAj9jF50y093bnJv08Tsfd8dLj1TQum1ocafB22Fn3it+YDZacxzLgyRkzN/dQF9LN+GTzjqqmUYoj48raLqStL6bdqYkVhp9HaT2nh06B7AvSqMv0XPPlBlY+gMEiqh+XAZZToOmPIAhbYJNi3kfXHVQrIJTndawPxs9DVo11WJmgWSBL6yb6V3z7DFgH8He7YPFItjPiDxp8aiGU2kEOjIXtiKkO30GjQHQuDt1X/sobMlx+8CjonsGUTHpe8YkegPpBKu+Qxp3d3sRB3lQwFrG+TtmGhr5H58COq5/+1i7CLXbH5ttwhafQEFdStfPk19m/65JEM2WeJRrQii/QZxNTE/fZNFxxgKmOS+ohCqwDDB5eZ6dhWqLkkMclT0lQ/Uu/CAH+StwZ+2GWg4NykBwFMwoaqeCKjdP9Y03jBTVcbI2lqnKj6LDMkbwLF/MMnuOwZGl2pwQWTGSlY5qKGCtjxT87V8FxcBzxzB6/gw86KFBBFOHffa4gyFiFCcJ0l9w+RtpO5kIBys=
    POSTGRES_USER: AgBnCPj7PfeVqW+qfpy/y0HAn153rjIIEPpSt+XymanmDTT41bUbbIJVbB1rbBI0c+Wx9dIZiPw9oP1JHS2Es+pSC5cMn4F1OYjg1hB4WgdC/ZDBjX3DeDSEsTJsmwZpgLETtgDnfVQKT4lyN7ZU2yjdwkoLMIis34VzHc/+/SClT3rNcfqfXLK5kgrF9l/xm6kAvt974N27sb+GI8vE4SLUgR2h/nHARYiO5FbOktDgto1bGstAvJRcbt26xdseiA90a/9xjFrUaeMl7LejB+3epgTmD32qf+CAlyHSxG87CEAcig4aNuxuA5dx6AY2qJRFk8I3ylPSIqFFmWgoIr72tcWQ4raZNmHqZiWUJfdM5MpapO+cN9GptTMLVSXCIEtUs3jW/ukzzGwSfkCj136wvGE9fnbWQ951nv8s6Fkg/DqSrF6r7S6P6w0EubZRdtqbMOXNuWt+dLdYYsD+NgDQzYfOq3BAoaChAA7Wf7Mgo0YwOR4EFWoFP9xh6mvAHPcwbkB3XyfVd+E2xN+dBzHwcRRYErfcLcMi9TTwAaamU/YFN9FewlA9gBYE7dEeeQ1+W2abBzNfTqKZspEyUZCqZqxQ+NuwPU0oooDdLOqtvnhbSpWNWiei0KpVN1NQT2Itdcxsg8GWaqE8rRunUP4B7/Jq6jBElW9HvucBiJ8M8lrEN+X2uEv+rJ/QBzS8lyzgS0IEXw==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: default

