apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-name
  namespace: default
spec:
  encryptedData:
    foo: AgBWJXcbHXMrg+7h/zqcw0ndfoMGuKmTYuFss7ckVHJ7ofU9AGd9BHbjWiQ/Vx7OoPoApbQCHsve0JdJSAn81M0IjYqpPFtsGahChxWXwQasAZYsjnW+iZKbqzLVMixPaGVmCdMNOG2dFicWMGfiOQqZi2/z3hgU74i78o0YMXZlLnMd99Vkp2hm68tuUpnXRRxMPwkz7nIOqp9D4Bng3Xya1nF2T+49vK5X8YOTPlsxu/kZ+g+SHprn+SBzMPcmOt1u4cbM5uhI2vBb0SU8Ro0ad+BxgsFDBNC0RPC2W2RzvQGKbWqMEaGU86UW7nyySWCApsfDROren8M3MSRMpXDwjo1kLWvPWHHZdFy5wCTRApfoqLldyFTTeRbVajIV5Y9jOfZFZagcfSofQ1/btS37MjfpsNUCIErW1cLSkPdHTwBiD2qtuDS2n01tDa1spcBKoJxfn4IAlVjpR/kGNnm0yJYpzkQyf6yNPUF+sJ4P620t4ToZ9DOxMLVRrLH7xi2j/7wlNjgZIdUb5VE3QFhtn5tCxPRp0MvMgAwOqdb6ZWascadPk2QSypDVrzUYif1zWzxhZLXoVDzHN57aNUA/IrIIqTdGgTW1IJpwD7iCl3ZbttE1e8gyCK7W9cMzftalDNn8w2b10BdrYJSNKeCACwL4pSZs8nVp2oliIOasLtXAkMG2ffHw4gNjiHVQ2OBNPFU=
  template:
    metadata:
      creationTimestamp: null
      name: secret-name
      namespace: default

