resources:
  - ../../base/
  - ../../base/adminer
  - ../../base/ingress
  - ../../base/postgres-db/
  - ../../base/storage/
secretGenerator:
  - name: postgres-secret
    envs:
      - .postgres.secret