resources:
  - ../../base/
  - ../../base/adminer
  - ../../base/ingress
  - ../../base/postgres-db/
  - ../../base/storage/
  - sealedSecrets/sealed-secret-postgres.yaml
  - sealedSecrets/sealed-secret-stripe.yaml
  - sealedSecrets/sealed-secret-auth.yaml
# --------------- Patches for skaffold, don't support digest when tagging the image name-----------------
# if is necessary to differentiate minikube context, create a skaffold profile
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: jym272/ticketing-frontend
    target:
      name: frontend
      kind: Deployment
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: jym272/ticketing-auth-api
    target:
      name: auth-api
      kind: Deployment
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: jym272/ticketing-expiration-api
    target:
        name: expiration-api
        kind: Deployment
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: jym272/ticketing-orders-api
    target:
        name: orders-api
        kind: Deployment
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: jym272/ticketing-payments-api
    target:
        name: payments-api
        kind: Deployment
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: jym272/ticketing-tickets-api
    target:
        name: tickets-api
        kind: Deployment
