resources:
  - ../../base/
  - ../../base/adminer
  - ../../base/ingress
  - ../../base/postgres-db/
  - ../../base/storage/
  - sealedSecrets/sealed-secret-postgres.yaml
  - sealedSecrets/sealed-secret-stripe.yaml
  - sealedSecrets/sealed-secret-auth.yaml