apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-orders-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-sc
  hostPath:
    path: /data/postgres-orders
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-orders-pvc
spec:
  storageClassName: postgres-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

