apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-tickets-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-sc
  hostPath:
    path: /data/postgres-tickets
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-tickets-pvc
spec:
  storageClassName: postgres-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

