resources:
  - ../../base/
  - ../../base/postgres-db/
  - ../../base/storage/
  - ../../base/adminer
secretGenerator:
  - name: postgres-secret
    envs:
      - .postgres.secret
configMapGenerator:
  - name: postgres-host
    envs:
      - .env
