resources:
  - ../../base/
  - ../../base/postgres-db/
  - ../../base/adminer
  - storage/
secretGenerator:
  - name: postgres-secret
    envs:
      - .postgres.secret
configMapGenerator:
  - name: postgres-host
    envs:
      - .env
