resources:
  - ../../base/
  - ../../base/adminer
  - ../../base/ingress
  - ../../base/postgres-db/
  - ../../base/storage/
  - ../../base/storage/pvc
secretGenerator:
  - name: postgres-secret
    envs:
      - .postgres.secret
configMapGenerator:
  - name: postgres-host
    envs:
      - .postgres_host.env
