apiVersion: v1
kind: Service
metadata:
  name: db-auth
spec:
  selector:
    db: auth
  ports:
    - protocol: TCP
      port: 5432
      name: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      db: auth
  template:
    metadata:
      labels:
        db: auth
    spec:
      containers:
        - name: db-auth
          image: postgres:15.1
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: jorge
            - name: POSTGRES_DB
              value: auth
            - name: POSTGRES_PASSWORD
              value: "123456"
          livenessProbe:
            exec:
              command: ["psql", "-U", "jorge", "-d", "auth", "-c", "SELECT 1"]
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 2
          readinessProbe:
            exec:
              command: ["psql", "-U", "jorge", "-d", "auth", "-c", "SELECT 1"]
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 2




