apiVersion: v1
kind: Service
metadata:
  name: db-auth
spec:
  clusterIP: None
  selector:
    db: auth
  ports:
    - protocol: TCP
      port: 5432
      name: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-auth
  annotations:
    datree.skip/CONTAINERS_INCORRECT_READONLYROOTFILESYSTEM_VALUE: too much overhead to implement this.
spec:
  selector:
    matchLabels:
      db: auth
  serviceName: "db-auth"
  replicas: 1 # the same number of volumes is needed
  minReadySeconds: 10
  template:
    metadata:
      labels:
        db: auth
    spec:
      initContainers:
        - name: create-dir-if-not-exists
          imagePullPolicy: IfNotPresent
          image: busybox:1.36.0
          command:
            - /bin/sh
            - -c
            - |
              if [ ! -d /var/lib/postgresql/data/pgdata ]; then
                mkdir -p /var/lib/postgresql/data/pgdata
                chown -R 10001:10000 /var/lib/postgresql/data/pgdata
                echo "created directory /var/lib/postgresql/data/pgdata"
              else
                echo "directory /var/lib/postgresql/data/pgdata already exists"
              fi
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: auth-claim
      containers:
        - name: db-auth
          image: postgres:15.2
          imagePullPolicy: IfNotPresent
          securityContext:
            seccompProfile:
              type: Unconfined # supported values: "Localhost", "RuntimeDefault"(doesnt work wit liveness), "Unconfined"
            capabilities:
              drop: [ "NET_RAW" ]
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: sealed-secret-postgres
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              value: auth
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sealed-secret-postgres
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          livenessProbe:
            exec:
              command: ["psql", "-U", "jorge", "-d", "auth", "-c", "SELECT 1"]
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 2
          readinessProbe:
            exec:
              command: ["psql", "-U", "jorge", "-d", "auth", "-c", "SELECT 1"]
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 2
          startupProbe:
            exec:
              command: ["pg_isready", "-U", "jorge", "-d", "auth"]
            periodSeconds: 1
            failureThreshold: 30
          resources:
            requests:
              cpu: 40m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - mountPath: var/lib/postgresql/data
              name: auth-claim
#            - mountPath: var/run/secrets/kubernetes.io/serviceaccount
#              name: auth-claim
#              readOnly: true
      volumes:
        - name: auth-claim
          persistentVolumeClaim:
            claimName: postgres-auth-pvc
#  volumeClaimTemplates:
#    - metadata:
#        name: auth-claim
#      spec:
#        accessModes:
#          - ReadWriteOnce
#        resources:
#          requests:
#            storage: 1Gi
#        storageClassName: postgres-auth-sc




