apiVersion: v1
kind: Service
metadata:
  name: db-payments
spec:
  clusterIP: None
  selector:
    db: payments
  ports:
    - protocol: TCP
      port: 5432
      name: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-payments
spec:
  selector:
    matchLabels:
      db: payments
  serviceName: "db-payments"
  replicas: 1 # the same number of volumes is needed
  minReadySeconds: 10
  template:
    metadata:
      labels:
        db: payments
    spec:
      containers:
        - name: db-payments
          image: postgres:15.1
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: jorge
            - name: POSTGRES_DB
              value: payments
            - name: POSTGRES_PASSWORD
              value: "123456"
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          livenessProbe:
            exec:
              command: ["psql", "-U", "jorge", "-d", "payments", "-c", "SELECT 1"]
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 2
          readinessProbe:
            exec:
              command: ["psql", "-U", "jorge", "-d", "payments", "-c", "SELECT 1"]
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 2
          volumeMounts:
            - mountPath: var/lib/postgresql/data
              name: payments-claim
      volumes:
        - name: payments-claim
          persistentVolumeClaim:
            claimName: postgres-payments-pvc




