apiVersion: v1
kind: Service
metadata:
  name: db-tickets
spec:
  clusterIP: None
  selector:
    db: tickets
  ports:
    - protocol: TCP
      port: 5432
      name: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-tickets
spec:
  selector:
    matchLabels:
      db: tickets
  serviceName: "db-tickets"
  replicas: 1 # the same number of volumes is needed
  minReadySeconds: 10
  template:
    metadata:
      labels:
        db: tickets
    spec:
      containers:
        - name: db-tickets
          image: postgres:15.1
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: jorge
            - name: POSTGRES_DB
              value: tickets
            - name: POSTGRES_PASSWORD
              value: "123456"
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          livenessProbe:
            exec:
              command: ["psql", "-U", "jorge", "-d", "tickets", "-c", "SELECT 1"]
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 2
          readinessProbe:
            exec:
              command: ["psql", "-U", "jorge", "-d", "tickets", "-c", "SELECT 1"]
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 2
          volumeMounts:
            - mountPath: var/lib/postgresql/data
              name: tickets-claim
      volumes:
        - name: tickets-claim
          persistentVolumeClaim:
            claimName: postgres-tickets-pvc





