apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-auth-sc
provisioner: kubernetes.io/no-provisioner
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-auth-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-auth-sc
  hostPath:
    path: /data/postgres-auth
