apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-orders-sc
provisioner: kubernetes.io/no-provisioner
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-orders-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-orders-sc
  hostPath:
    path: /data/postgres-orders
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-orders-pvc
spec:
  storageClassName: postgres-orders-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

