apiVersion: v1
kind: Service
metadata:
  name: my-frontend
  labels:
    app: mypod
spec:
  clusterIP: None
  selector:
    app: mypod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
# nc -vz my-csi-app-set-1.my-frontend.default.svc.cluster.local 80
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-csi-app-set
spec:
  selector:
    matchLabels:
      app: mypod
  serviceName: "my-frontend"
  replicas: 2
  template:
    metadata:
      labels:
        app: mypod
    spec:
      containers:
        - name: hello-from
          image: pbitty/hello-from:latest
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - mountPath: "/data"
              name: csi-pvc
  volumeClaimTemplates:
    - metadata:
        name: csi-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: do-block-storage




