apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-payments-sc
volumeBindingMode: Immediate
reclaimPolicy: Delete
provisioner: kubernetes.io/no-provisioner
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-payments-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: postgres-payments-sc
  nfs:
    server: 192.168.122.1
    path: /data/postgres-payments
