apiVersion: v1
kind: Service
metadata:
  name: auth-api
spec:
  selector:
    api: auth
  ports:
    - protocol: TCP
      port: 3050
      name: auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  labels:
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      api: auth
  template:
    metadata:
      labels:
        api: auth
    spec:
      initContainers:
        - name: wait-for-postgres
          imagePullPolicy: IfNotPresent
          image: busybox:1.36.0
          command:
            [
              "sh",
              "-c",
              "until nc -vz db-auth.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local 5432; do echo waiting for db auth; sleep 2; done",
            ]
      containers:
        - name: auth-api
          image: jym272/ticketing-auth-api
          readinessProbe:
            httpGet:
              path: /health
              port: 3050
            periodSeconds: 5
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 3050
            periodSeconds: 10
            failureThreshold: 2
          startupProbe:
            httpGet:
              path: /health
              port: 3050
            failureThreshold: 30
            periodSeconds: 1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          env:
            - name: FORCE_COLOR
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: FORCE_COLOR
            - name: PORT
              value: "3050"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: sealed-secret-postgres
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              value: auth
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sealed-secret-postgres
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-host
                  key: POSTGRES_HOST_AUTH
            - name: POSTGRES_PORT
              value: "5432"
            - name: PASSWORD_PEPPER
              valueFrom:
                secretKeyRef:
                  name: sealed-secret-auth
                  key: PASSWORD_PEPPER
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sealed-secret-auth
                  key: JWT_SECRET
