apiVersion: v1
kind: Service
metadata:
  name: expiration-api
spec:
  selector:
    api: expiration
  ports:
    - protocol: TCP
      port: 3053
      name: expiration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-api
  labels:
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      api: expiration
  template:
    metadata:
#      annotations:
#        seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
      labels:
        api: expiration
    spec:
      initContainers:
        - name: wait-for-nats
          imagePullPolicy: IfNotPresent
          image: busybox:1.36.0
          command:
            [
              "sh",
              "-c",
              "until nc -vz nats.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local 4222; do echo waiting for nats; sleep 2; done",
            ]
        - name: wait-for-redis
          imagePullPolicy: IfNotPresent
          image: busybox:1.36.0
          command:
              [
              "sh",
              "-c",
              "until nc -vz redis.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local 6379; do echo waiting for redis; sleep 2; done",
              ]
      containers:
        - name: expiration-api
          image: jym272/ticketing-expiration-api
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: [ "NET_RAW" ]
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10000
          readinessProbe: # connection to nats -> fundamental to microservice
            httpGet:
              path: /api/healthz  # /api/healthz
              port: 3053
            periodSeconds: 5
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /health  # /api/healthz
              port: 3053
            periodSeconds: 10
            failureThreshold: 2
          startupProbe: #express service
            httpGet:
              path: /health
              port: 3053
            failureThreshold: 30
            periodSeconds: 1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          env:
            - name: FORCE_COLOR
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: FORCE_COLOR
            - name: PORT
              value: "3053"
            - name: NATS_SERVER_HOST
              value: nats.default.svc.cluster.local
            - name: NATS_SERVER_PORT
              value: "4222"
            - name: NACK_DELAY_MS
              value: "1000"
            - name: REDIS_HOST
              value: redis.default.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
