apiVersion: v1
kind: Service
metadata:
  name: expiration-api
spec:
  selector:
    api: expiration
  ports:
    - protocol: TCP
      port: 3053
      name: expiration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-api
spec:
  replicas: 1
  selector:
    matchLabels:
      api: expiration
  template:
    metadata:
      labels:
        api: expiration
    spec:
      initContainers:
        - name: wait-for-nats
          imagePullPolicy: IfNotPresent
          image: busybox:1.36.0
          command:
            [
              "sh",
              "-c",
              "until nc -vz nats.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local 4222; do echo waiting for nats; sleep 2; done",
            ]
        - name: wait-for-redis
          imagePullPolicy: IfNotPresent
          image: busybox:1.36.0
          command:
              [
              "sh",
              "-c",
              "until nc -vz redis.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local 6379; do echo waiting for redis; sleep 2; done",
              ]
      containers:
        - name: expiration-api
          image: jym272/ticketing-expiration-api
          livenessProbe: # connection to nats -> fundamental to microservice
            httpGet:
              path: /api/healthz  # /api/healthz
              port: 3053
            periodSeconds: 5
            failureThreshold: 1
          startupProbe: #express service
            httpGet:
              path: /health
              port: 3053
            failureThreshold: 60
            periodSeconds: 1
          env:
            - name: PORT
              value: "3053"
            - name: NATS_SERVER_HOST
              value: nats.default.svc.cluster.local
            - name: NATS_SERVER_PORT
              value: "4222"
            - name: NACK_DELAY_MS
              value: "1000"
            - name: REDIS_HOST
              value: redis.default.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
