apiVersion: v1
kind: Service
metadata:
  name: orders-api
spec:
  selector:
    api: orders
  ports:
    - protocol: TCP
      port: 3052
      name: orders
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-api
  labels:
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      api: orders
  template:
    metadata:
      labels:
        api: orders
    spec:
      initContainers:
        - name: wait-for-postgres
          imagePullPolicy: IfNotPresent
          image: busybox:1.36.0
          command:
            [
              "sh",
              "-c",
              "until nc -vz db-orders.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local 5432; do echo waiting for db orders; sleep 2; done",
            ]
        - name: wait-for-nats
          imagePullPolicy: IfNotPresent
          image: busybox:1.36.0
          command:
            [
              "sh",
              "-c",
              "until nc -vz nats.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local 4222; do echo waiting for nats; sleep 2; done",
            ]
      containers:
        - name: orders-api
          image: jym272/ticketing-orders-api
          securityContext:
            allowPrivilegeEscalation: false
          readinessProbe: # connection to nats -> fundamental to microservice
            httpGet:
              path: /api/healthz  # /api/healthz
              port: 3052
            periodSeconds: 5
            failureThreshold: 1
          livenessProbe: # connection to nats -> fundamental to microservice
            httpGet:
              path: /health  # /api/healthz
              port: 3052
            periodSeconds: 10
            failureThreshold: 2
          startupProbe: #express service
            httpGet:
              path: /health
              port: 3052
            failureThreshold: 30
            periodSeconds: 1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          env:
            - name: EXPIRATION_ORDER_MINUTES
              value: "1"
            - name: FORCE_COLOR
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: FORCE_COLOR
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sealed-secret-auth
                  key: JWT_SECRET
            - name: NACK_DELAY_MS
              value: "1000"
            - name: NACK_MAX_RETRIES
              value: "3"
            - name: NATS_SERVER_HOST
              value: nats.default.svc.cluster.local
            - name: NATS_SERVER_PORT
              value: "4222"
            - name: PORT
              value: "3052"
            - name: POSTGRES_DB
              value: orders
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-host
                  key: POSTGRES_HOST_ORDERS
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sealed-secret-postgres
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: sealed-secret-postgres
                  key: POSTGRES_USER