apiVersion: v1
kind: Service
metadata:
  name: orders-api
spec:
  selector:
    api: orders
  ports:
    - protocol: TCP
      port: 3052
      name: orders
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-api
spec:
  replicas: 1
  selector:
    matchLabels:
      api: orders
  template:
    metadata:
      labels:
        api: orders
    spec:
      initContainers:
        - name: wait-for-postgres
          imagePullPolicy: IfNotPresent
          image: busybox:1.36.0
          command:
            [
              "sh",
              "-c",
              "until nc -vz db-orders.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local 5432; do echo waiting for db orders; sleep 2; done",
            ]
        - name: wait-for-nats
          imagePullPolicy: IfNotPresent
          image: busybox:1.36.0
          command:
            [
              "sh",
              "-c",
              "until nc -vz nats.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local 4222; do echo waiting for nats; sleep 2; done",
            ]
      containers:
        - name: orders-api
          image: jym272/ticketing-orders-api
          livenessProbe: # connection to nats -> fundamental to microservice
            httpGet:
              path: /api/healthz  # /api/healthz
              port: 3052
            periodSeconds: 5
            failureThreshold: 1
          startupProbe: #express service
            httpGet:
              path: /health
              port: 3052
            failureThreshold: 30
            periodSeconds: 1
          env:
            - name: PORT
              value: "3052"
            - name: POSTGRES_USER
              value: jorge
            - name: POSTGRES_DB
              value: orders
            - name: POSTGRES_PASSWORD
              value: "123456"
            - name: POSTGRES_HOST
              value: db-orders.default.svc.cluster.local
            - name: POSTGRES_PORT
              value: "5432"
            - name: NATS_SERVER_HOST
              value: nats.default.svc.cluster.local
            - name: NATS_SERVER_PORT
              value: "4222"
            - name: NACK_DELAY_MS
              value: "1000"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_SECRET