apiVersion: v1
kind: Service
metadata:
  name: tickets-api
spec:
  selector:
    api: tickets
  ports:
    - protocol: TCP
      port: 3051
      name: tickets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-api
spec:
  replicas: 1
  selector:
    matchLabels:
      api: tickets
  template:
    metadata:
      labels:
        api: tickets
    spec:
      initContainers:
        - name: wait-for-postgres
          imagePullPolicy: IfNotPresent
          image: busybox:1.36.0
          command:
            [
              "sh",
              "-c",
              "until nc -vz db-tickets.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local 5432; do echo waiting for db tickets; sleep 2; done",
            ]
        - name: wait-for-nats
          imagePullPolicy: IfNotPresent
          image: busybox:1.36.0
          command:
            [
              "sh",
              "-c",
              "until nc -vz nats.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local 4222; do echo waiting for nats; sleep 2; done",
            ]
      containers:
        - name: tickets-api
          image: jym272/ticketing-tickets-api
          livenessProbe: # connection to nats -> fundamental to microservice
            httpGet:
              path: /api/healthz  # /api/healthz
              port: 3051
            periodSeconds: 5
            failureThreshold: 1
          startupProbe: #express service
            httpGet:
              path: /health
              port: 3051
            failureThreshold: 30
            periodSeconds: 1
          env:
            - name: FORCE_COLOR
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: FORCE_COLOR
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_SECRET
            - name: NACK_DELAY_MS
              value: "1000"
            - name: NACK_MAX_RETRIES
              value: "3"
            - name: NATS_SERVER_HOST
              value: nats.default.svc.cluster.local
            - name: NATS_SERVER_PORT
              value: "4222"
            - name: PORT
              value: "3051"
            - name: POSTGRES_DB
              value: tickets
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-host
                  key: POSTGRES_HOST_TICKETS
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sealed-secret-postgres
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: sealed-secret-postgres
                  key: POSTGRES_USER
