resources:
- ../../base/
- ../../base/postgres-db
- sc-gp3.yaml
#- ingress2.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- patch: |-
    - op: remove
      path: /spec/template/spec/volumes
    - op: add
      path: /spec/volumeClaimTemplates
      value:
        - metadata:
            name: auth-claim
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            storageClassName: gp3
  target:
    name: db-auth
    kind: StatefulSet
- patch: |-
    - op: remove
      path: /spec/template/spec/volumes
    - op: add
      path: /spec/volumeClaimTemplates
      value:
        - metadata:
            name: orders-claim
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            storageClassName: gp3
  target:
    name: db-orders
    kind: StatefulSet
- patch: |-
    - op: remove
      path: /spec/template/spec/volumes
    - op: add
      path: /spec/volumeClaimTemplates
      value:
        - metadata:
            name: payments-claim
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            storageClassName: gp3
  target:
    name: db-payments
    kind: StatefulSet
- patch: |-
    - op: remove
      path: /spec/template/spec/volumes
    - op: add
      path: /spec/volumeClaimTemplates
      value:
        - metadata:
            name: tickets-claim
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            storageClassName: gp3
  target:
    name: db-tickets
    kind: StatefulSet
  # take out the volumeMounts from redis and nats, add block storage
- patch: |-
    - op: remove
      path: /spec/template/spec/volumes
    - op: add
      path: /spec/volumeClaimTemplates
      value:
        - metadata:
            name: redis-claim
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            storageClassName: gp3
  target:
    name: redis
    kind: StatefulSet
- patch: |-
    - op: remove
      path: /spec/template/spec/volumes
    - op: add
      path: /spec/volumeClaimTemplates
      value:
        - metadata:
            name: nats-claim
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            storageClassName: gp3
  target:
    name: nats
    kind: StatefulSet
# set INGRESS_NS and INGRESS_SVC env vars for frontend
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: default
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: nginx-ingress-ingress-nginx-controller
  target:
    kind: Deployment
    name: frontend

secretGenerator:
  - name: postgres-secret
    envs:
      - .postgres.secret
configMapGenerator:
  - name: postgres-host
    envs:
      - .postgres_host.env