apiVersion: v1
kind: Service
metadata:
  name: nats
spec:
  clusterIP: None
  selector:
    app: nats
  ports:
    - protocol: TCP
      port: 4222
      name: nats-client
    - protocol: TCP
      port: 8222
      name: nats-monitoring
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats
  labels:
    app: nats
spec:
  selector:
    matchLabels:
      app: nats
  serviceName: "nats"
  replicas: 1 # the same number of volumes is needed
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: nats
    spec:
      initContainers:
        - name: create-dir-if-not-exists
          imagePullPolicy: IfNotPresent
          image: busybox:1.36.0
          command:
            - /bin/sh
            - -c
            - |
              if [ ! -d /data/natsData ]; then
                mkdir -p /data/natsData
                chown -R 10001:10000 /data/natsData
                echo "created directory /data/natsData"
              else
                echo "directory /data/natsData already exists"
              fi
          volumeMounts:
            - mountPath: /data
              name: nats-claim
      containers:
        - name: nats
          image: nats:2.9.16-alpine3.17
          securityContext:
            capabilities:
              drop: [ "NET_RAW" ]
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10000
          command:
            - nats-server
            - -js
            - --store_dir=/data/natsData
            - -DV
            - -m
            - "8222"
          volumeMounts:
            - mountPath: /data
              name: nats-claim
          readinessProbe:
            httpGet:
              path: /healthz?js-enabled-only=true
              port: 8222
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /healthz?js-enabled-only=true
              port: 8222
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 2
          resources:
            requests:
              cpu: 30m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 256Mi
      volumes:
        - name: nats-claim
          persistentVolumeClaim:
            claimName: jetstream-pvc
#  volumeClaimTemplates:
#    - metadata:
#        name: nats-claim
#      spec:
#        accessModes:
#          - ReadWriteOnce
#        resources:
#          requests:
#            storage: 1Gi
#        storageClassName: jetstream-sc



