apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    api: frontend
  ports:
    - protocol: TCP
      port: 3000
      name: frontend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      api: frontend
  template:
    metadata:
      labels:
        api: frontend
    spec:
      containers:
        - name: frontend
          image: jym272/ticketing-frontend
          securityContext:
            allowPrivilegeEscalation: false
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            periodSeconds: 5
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            periodSeconds: 10
            failureThreshold: 2
          startupProbe:
            httpGet:
              path: /api/health
              port: 3000
            failureThreshold: 30
            periodSeconds: 1
          resources:
            requests:
              cpu: 30m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          # maintain the order of env vars for kustomization patches
          env:
            # kubectl get ns
            - name: INGRESS_NS # the ns where resides the ingress i.e: default, ingress-nginx
              value: ingress-nginx
            # kubectl get svc -n ingress-nginx # or de ns where the ingress resides
            - name: INGRESS_SVC
              value: ingress-nginx-controller
            - name: STRIPE_PUBLISHABLE_KEY
              valueFrom:
                  secretKeyRef:
                    name: sealed-secret-stripe
                    key: STRIPE_PUBLISHABLE_KEY



