resources:
- ../../base/

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: patches/apis-init-container-cmd.yaml
  target:
    kind: Deployment
    name: auth-api
- path: patches/apis-init-container-cmd.yaml
  target:
      kind: Deployment
      name: orders-api
- path: patches/apis-init-container-cmd.yaml
  target:
    kind: Deployment
    name: payments-api
- path: patches/apis-init-container-cmd.yaml
  target:
    kind: Deployment
    name: tickets-api
- patch: |-
    - op: remove
      path: /spec/template/spec/containers/0/volumeMounts
    - op: remove
      path: /spec/template/spec/volumes
  target:
    name: redis-deployment
    kind: Deployment
- patch: |-
    - op: remove
      path: /spec/template/spec/containers/0/volumeMounts
    - op: remove
      path: /spec/template/spec/volumes
  target:
    kind: Deployment
    name: nats
secretGenerator:
  - name: postgres-secret
    envs:
      - .postgres.secret
configMapGenerator:
  - name: postgres-host
    envs:
      - .env