resources:
- ../../base/

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: patches/apis-init-container-cmd.yaml
  target:
    kind: Deployment
    name: auth-api
- path: patches/apis-init-container-cmd.yaml
  target:
      kind: Deployment
      name: orders-api
- path: patches/apis-init-container-cmd.yaml
  target:
    kind: Deployment
    name: payments-api
- path: patches/apis-init-container-cmd.yaml
  target:
    kind: Deployment
    name: tickets-api
secretGenerator:
  - name: postgres-secret
    envs:
      - .postgres.secret
configMapGenerator:
  - name: postgres-host
    envs:
      - .env