name: reusable-k8s-policy-check
on:
  workflow_call:
jobs:
  k8sPolicyCheck:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v3
      - name: run datree policy check
        uses: datreeio/action-datree@main
        env:
          DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }}
        with:
          isKustomization: true
          path: 'k8s/overlay/digitalOcean'
          cliArguments: '--verbose --policy-config policies.yaml -p digitalOcean'
