name: pull_request

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'k8s/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  k8sPolicyCheck:
    uses: ./.github/workflows/k8s-policy-check.yml
    secrets: inherit