name: pull_request

on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  k8sPolicyCheck:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      -
        uses: actions/checkout@v3
      -
        name: run datree policy check
        uses: datreeio/action-datree@main
        env:
          DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }}
        with:
          isKustomization: true
          path: 'k8s/overlay/digitalOcean'
          cliArguments: '--verbose --policy-config policies.yaml -p digitalOcean'
      -
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      -
        name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.DIGITALOCEAN_CLUSTER_ID }}
      -
        name: Apply kustomization
        run: kubectl apply -k k8s/overlay/digitalOcean

#      - name: docker login
#        env:
#          DOCKER_USER: ${{ secrets.DOCKER_USER }}
#          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#        run: |
#          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
#      - name: build
#        run: |
#          docker build ./c# -t aimvector/csharp:1.0.0
#      - name: push
#        run: |
#          docker push aimvector/csharp:1.0.0
#      - name: deploy
#        run: |
#          echo 'deploying...'
